[workspace]
resolver = "2"
members = ["crates/cairn-cli", "crates/cairn-scip", "crates/cairn-store", "crates/cairn-fmt"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
cairn-scip = { path = "crates/cairn-scip" }
cairn-store = { path = "crates/cairn-store" }
cairn-fmt = { path = "crates/cairn-fmt" }

anyhow = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
clap = { version = "4", features = ["derive"] }
blake3 = "1"

[profile.release]
opt-level = 3
lto = "thin"
