//! Loading a SCIP index into the projection.
//!
//! This is the bulk path from architecture 4.1. It is deliberately not incremental:
//! the phase 0 spike showed the upstream indexers are not incremental either, so the
//! fast path for edits is the language server (4.2), not a faster ingest.

use crate::batch::BatchWriter;
use crate::{schema, GeneratedVia, Lang, Store};
use anyhow::{Context, Result};
use cairn_scip::ParsedSymbol;
use rusqlite::params;
use rusqlite::types::Value;
use std::collections::HashMap;
use std::io::Read;
use std::path::Path;

/// Markers that a file is generated. Checked against the head of the file, which is
/// the only trustworthy signal — filename patterns are not (see the retraction in
/// docs/spike-0-results.md section 5: 48k lines of generated code lived in files
/// named `__init__.py`).
const GENERATED_MARKERS: &[&str] = &[
    "Code generated by",
    "DO NOT EDIT",
    "@generated",
    "Generated by the protocol buffer compiler",
    "Generated by the gRPC Python protocol compiler",
    "autogenerated",
    "AUTO-GENERATED",
];

/// How much of a file to read when looking for a generated marker. Generators put
/// their banner in the first few lines; reading more would cost I/O for nothing.
const MARKER_SCAN_BYTES: usize = 2048;

#[derive(Debug, Default, Clone)]
pub struct IngestStats {
    pub documents: usize,
    pub symbols: usize,
    pub occurrences: usize,
    pub generated_files: usize,
    pub marker_detected: usize,
    pub skipped_local: usize,
    pub batch_flushes: usize,
    /// Sub-directory the index's paths were rooted at, e.g. "srcpy".
    pub path_prefix: String,
    /// Definitions carrying an enclosing range - the ones that can contain a call.
    pub with_enclosing: usize,
    pub implements_edges: usize,
    pub test_files: usize,
}

/// Interns strings, keeping an in-process cache so the common case never touches SQLite.
struct Interner<'a> {
    conn: &'a rusqlite::Connection,
    cache: HashMap<String, i64>,
}

impl<'a> Interner<'a> {
    fn new(conn: &'a rusqlite::Connection) -> Self {
        Interner {
            conn,
            cache: HashMap::with_capacity(64 * 1024),
        }
    }

    fn intern(&mut self, s: &str) -> Result<i64> {
        if let Some(&id) = self.cache.get(s) {
            return Ok(id);
        }
        self.conn
            .execute("INSERT OR IGNORE INTO strings(s) VALUES (?1)", params![s])?;
        let id: i64 = self
            .conn
            .query_row("SELECT id FROM strings WHERE s = ?1", params![s], |r| {
                r.get(0)
            })?;
        self.cache.insert(s.to_string(), id);
        Ok(id)
    }
}

/// Ingest one SCIP index.
///
/// `repo_root` is optional. When given, file heads are read to detect generated code
/// by marker; without it detection falls back to path patterns and says so via
/// `gen_via`, so the weaker signal is never silently presented as the strong one.
pub fn ingest_scip(store: &mut Store, index_path: &Path, repo_root: Option<&Path>) -> Result<IngestStats> {
    let index = cairn_scip::load(index_path)?;
    let mut stats = IngestStats::default();

    // SCIP document paths are relative to the *indexer's* project root, which for a
    // multi-language repo is a subdirectory (srcpy/, srcgo/). Everything downstream
    // wants repo-relative paths: D13 forbids absolute paths so answers work both
    // inside the container and on the host, and two languages would otherwise collide
    // on identical relative paths. Resolve the prefix once, up front.
    let prefix = resolve_prefix(&index, repo_root);
    stats.path_prefix = prefix.clone();

    schema::tune_for_bulk_load(&store.conn)?;
    let tx = store.conn.transaction()?;
    {
        let mut interner = Interner::new(&tx);
        // Symbol string -> row id, so repeated occurrences do not re-hash and re-query.
        let mut symbol_ids: HashMap<String, i64> = HashMap::with_capacity(128 * 1024);

        // RETURNING gives us the row id without a second round trip; the DO UPDATE
        // is a no-op that exists only so the clause still fires on conflict.
        let mut insert_symbol = tx.prepare(
            "INSERT INTO symbols(hash, name_id, module_id, container_id, pkg_id, kind, lang)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
             ON CONFLICT(hash) DO UPDATE SET hash = excluded.hash
             RETURNING id",
        )?;
        let mut insert_file = tx.prepare(
            "INSERT INTO files(path_id, lang, generated, gen_via, is_test)
             VALUES (?1, ?2, ?3, ?4, ?5)
             ON CONFLICT(path_id) DO UPDATE SET lang = excluded.lang
             RETURNING id",
        )?;
        // Occurrences are the hot table - 350k rows on the spike corpus - so they go
        // through the batching queue rather than one statement per row.
        let mut occ_batch = BatchWriter::new(
            "occurrences",
            &["file_id", "symbol_id", "line", "col_start", "col_end", "role", "enc_end"],
        );
        // `implements` relations come straight from the index; unlike call edges they
        // need no derivation. On the spike corpus: 9,743 in Go, 2,549 in Python.
        let mut edge_batch = BatchWriter::new(
            "edges",
            &["src_symbol", "dst_symbol", "kind", "source", "confidence"],
        );

        for doc in &index.documents {
            let lang = detect_lang(doc);
            let (generated, via) = detect_generated(&join_prefix(&prefix, &doc.relative_path), repo_root);
            if generated {
                stats.generated_files += 1;
                if via == GeneratedVia::HeaderMarker {
                    stats.marker_detected += 1;
                }
            }

            let rel_path = join_prefix(&prefix, &doc.relative_path);
            let path_id = interner.intern(&rel_path)?;
            let is_test = crate::conventions::is_test_path(&rel_path);
            if is_test {
                stats.test_files += 1;
            }
            let file_id: i64 = insert_file.query_row(
                params![path_id, lang as i64, generated as i64, via as i64, is_test as i64],
                |r| r.get(0),
            )?;

            // Symbols declared by this document, then the occurrences that use them.
            for info in &doc.symbols {
                let src = intern_symbol(
                    &info.symbol,
                    lang,
                    &mut interner,
                    &mut insert_symbol,
                    &mut symbol_ids,
                    &mut stats,
                )?;
                for rel in &info.relationships {
                    if !rel.is_implementation || rel.symbol.is_empty() {
                        continue;
                    }
                    let dst = intern_symbol(
                        &rel.symbol,
                        lang,
                        &mut interner,
                        &mut insert_symbol,
                        &mut symbol_ids,
                        &mut stats,
                    )?;
                    edge_batch.push(
                        &tx,
                        vec![
                            Value::from(src),
                            Value::from(dst),
                            Value::from(crate::EdgeKind::Implements as i64),
                            Value::from(crate::EdgeSource::Scip as i64),
                            Value::from(1.0f64),
                        ],
                    )?;
                    stats.implements_edges += 1;
                }
            }

            for occ in &doc.occurrences {
                if occ.symbol.is_empty() {
                    continue;
                }
                if occ.symbol.starts_with("local ") {
                    // Function-local bindings are noise for navigation and would more
                    // than double the occurrence table.
                    stats.skipped_local += 1;
                    continue;
                }
                let symbol_id = intern_symbol(
                    &occ.symbol,
                    lang,
                    &mut interner,
                    &mut insert_symbol,
                    &mut symbol_ids,
                    &mut stats,
                )?;
                let (line, col_start, col_end) = occurrence_range(occ);
                let enc_end = enclosing_end_line(occ);
                if enc_end.is_some() {
                    stats.with_enclosing += 1;
                }
                occ_batch.push(
                    &tx,
                    vec![
                        Value::from(file_id),
                        Value::from(symbol_id),
                        Value::from(line),
                        Value::from(col_start),
                        Value::from(col_end),
                        Value::from(occ.symbol_roles as i64),
                        match enc_end {
                            Some(e) => Value::from(e),
                            None => Value::Null,
                        },
                    ],
                )?;
                stats.occurrences += 1;
            }
            stats.documents += 1;
        }
        let batch_stats = occ_batch.finish(&tx)?;
        stats.batch_flushes = batch_stats.flushes + edge_batch.finish(&tx)?.flushes;
    }
    tx.commit()?;

    schema::create_indexes(&store.conn)?;
    schema::finalize(&store.conn)?;
    store.set_meta("schema_version", &schema::SCHEMA_VERSION.to_string())?;
    Ok(stats)
}

#[allow(clippy::too_many_arguments)]
fn intern_symbol(
    symbol: &str,
    doc_lang: Lang,
    interner: &mut Interner,
    insert: &mut rusqlite::Statement,
    cache: &mut HashMap<String, i64>,
    stats: &mut IngestStats,
) -> Result<i64> {
    if let Some(&id) = cache.get(symbol) {
        return Ok(id);
    }
    let parsed = ParsedSymbol::parse(symbol);
    let name = parsed.as_ref().map(|p| p.display_name()).unwrap_or(symbol);
    let module = parsed.as_ref().map(|p| p.module()).unwrap_or("");
    let container = parsed.as_ref().and_then(|p| p.container());
    let pkg = parsed.as_ref().map(|p| p.package).unwrap_or("");
    let kind = parsed
        .as_ref()
        .map(|p| p.kind())
        .unwrap_or(cairn_scip::SymbolKind::Unknown);
    // A symbol's language comes from its own scheme, not from the document that
    // mentions it: a Go file may reference a symbol indexed by another tool.
    let lang = parsed
        .as_ref()
        .map(|p| Lang::from_scip_scheme(p.scheme))
        .filter(|l| *l != Lang::Unknown)
        .unwrap_or(doc_lang);

    let hash = crate::symbol_hash(symbol);
    let name_id = interner.intern(name)?;
    let module_id = if module.is_empty() {
        None
    } else {
        Some(interner.intern(module)?)
    };
    let container_id = match container {
        Some(c) if !c.is_empty() => Some(interner.intern(c)?),
        _ => None,
    };
    let pkg_id = if pkg.is_empty() {
        None
    } else {
        Some(interner.intern(pkg)?)
    };

    let id: i64 = insert.query_row(
        params![
            &hash[..],
            name_id,
            module_id,
            container_id,
            pkg_id,
            kind as i64,
            lang as i64
        ],
        |r| r.get(0),
    )?;
    cache.insert(symbol.to_string(), id);
    stats.symbols += 1;
    Ok(id)
}

fn join_prefix(prefix: &str, rel: &str) -> String {
    if prefix.is_empty() {
        rel.to_string()
    } else {
        format!("{prefix}/{rel}")
    }
}

/// Work out which sub-directory of the repo the index's paths hang off.
///
/// Verified against the filesystem rather than trusted: we take candidates from the
/// index metadata and check that document paths actually resolve. A wrong prefix would
/// silently disable marker-based generated-code detection, which is the exact failure
/// this function exists to prevent.
fn resolve_prefix(index: &cairn_scip::Index, repo_root: Option<&Path>) -> String {
    let Some(root) = repo_root else {
        return String::new();
    };
    let sample: Vec<&str> = index
        .documents
        .iter()
        .map(|d| d.relative_path.as_str())
        .filter(|p| !p.is_empty())
        .take(24)
        .collect();
    if sample.is_empty() {
        return String::new();
    }

    let mut candidates: Vec<String> = vec![String::new()];
    // The indexer records its own project root, e.g. "file:///work/srcpy".
    if let Some(meta) = &index.metadata {
        let pr = meta.project_root.trim_start_matches("file://");
        if let Some(base) = Path::new(pr).file_name().and_then(|s| s.to_str()) {
            if !base.is_empty() {
                candidates.push(base.to_string());
            }
        }
    }
    // Fall back to scanning one level down, for indexes with unhelpful metadata.
    if let Ok(entries) = std::fs::read_dir(root) {
        for e in entries.flatten() {
            if e.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                if let Some(name) = e.file_name().to_str() {
                    if !name.starts_with('.') {
                        candidates.push(name.to_string());
                    }
                }
            }
        }
    }

    let mut best = (0usize, String::new());
    for cand in candidates {
        let hits = sample
            .iter()
            .filter(|p| root.join(join_prefix(&cand, p)).exists())
            .count();
        if hits > best.0 {
            best = (hits, cand);
        }
    }
    best.1
}

/// Where an occurrence sits, as `(line, col_start, col_end)`, 0-based like SCIP.
///
/// The schema deprecated the packed `range` in favour of typed `single_line_range` /
/// `multi_line_range`, but the indexers we actually run (scip-go 0.2.7, scip-python
/// 0.6.6) still emit the packed form. Prefer the typed fields, fall back to packed.
/// Multi-line occurrences are recorded at their start line: navigation wants a place
/// to jump to, not an extent.
fn occurrence_range(occ: &cairn_scip::Occurrence) -> (i64, i64, i64) {
    use cairn_scip::proto::occurrence::TypedRange;
    match &occ.typed_range {
        Some(TypedRange::SingleLineRange(r)) => (
            r.line as i64,
            r.start_character as i64,
            r.end_character as i64,
        ),
        Some(TypedRange::MultiLineRange(r)) => (
            r.start_line as i64,
            r.start_character as i64,
            r.end_character as i64,
        ),
        None => {
            #[allow(deprecated)]
            decode_range(&occ.range)
        }
    }
}

/// Last line of the definition's body, if the indexer emitted an enclosing range.
///
/// This is what makes a call graph possible at all: SCIP carries no caller edges and
/// leaves `enclosing_symbol` empty, so the only way to answer "who calls this" is to
/// find the innermost definition whose body spans the reference (see
/// `schema::derive_call_edges`).
fn enclosing_end_line(occ: &cairn_scip::Occurrence) -> Option<i64> {
    use cairn_scip::proto::occurrence::TypedEnclosingRange;
    match &occ.typed_enclosing_range {
        Some(TypedEnclosingRange::SingleLineEnclosingRange(r)) => Some(r.line as i64),
        Some(TypedEnclosingRange::MultiLineEnclosingRange(r)) => Some(r.end_line as i64),
        None => {
            #[allow(deprecated)]
            let r = &occ.enclosing_range;
            match r.len() {
                3 => Some(r[0] as i64),
                4 => Some(r[2] as i64),
                _ => None,
            }
        }
    }
}

/// Packed legacy encoding: `[startLine, startCol, endLine, endCol]`, or
/// `[startLine, startCol, endCol]` when the range is on one line.
fn decode_range(range: &[i32]) -> (i64, i64, i64) {
    match range.len() {
        3 => (range[0] as i64, range[1] as i64, range[2] as i64),
        4 => (range[0] as i64, range[1] as i64, range[3] as i64),
        _ => (0, 0, 0),
    }
}

fn detect_lang(doc: &cairn_scip::Document) -> Lang {
    match doc.language.to_ascii_lowercase().as_str() {
        "python" => Lang::Python,
        "go" => Lang::Go,
        "typescript" | "javascript" | "tsx" => Lang::TypeScript,
        _ => match Path::new(&doc.relative_path)
            .extension()
            .and_then(|e| e.to_str())
        {
            Some("py") | Some("pyi") => Lang::Python,
            Some("go") => Lang::Go,
            Some("ts") | Some("tsx") | Some("js") | Some("jsx") => Lang::TypeScript,
            _ => Lang::Unknown,
        },
    }
}

/// Path patterns are the fallback of last resort, and are reported as such.
const GENERATED_PATH_HINTS: &[&str] = &[".pb.go", "_pb2.py", "_pb2_grpc.py", "_pb2.pyi"];

fn detect_generated(rel_path: &str, repo_root: Option<&Path>) -> (bool, GeneratedVia) {
    if let Some(root) = repo_root {
        let full = root.join(rel_path);
        if let Ok(mut f) = std::fs::File::open(&full) {
            let mut buf = vec![0u8; MARKER_SCAN_BYTES];
            if let Ok(n) = f.read(&mut buf) {
                let head = String::from_utf8_lossy(&buf[..n]);
                if GENERATED_MARKERS.iter().any(|m| head.contains(m)) {
                    return (true, GeneratedVia::HeaderMarker);
                }
                // The file was readable and carries no marker, so a path-pattern guess
                // would only add false positives. Trust the read.
                return (false, GeneratedVia::No);
            }
        }
    }
    if GENERATED_PATH_HINTS.iter().any(|h| rel_path.contains(h)) {
        return (true, GeneratedVia::PathPattern);
    }
    (false, GeneratedVia::No)
}

/// Ingest with a friendlier error when the file is missing.
pub fn ingest_path(store: &mut Store, path: &Path, repo_root: Option<&Path>) -> Result<IngestStats> {
    if !path.exists() {
        anyhow::bail!("SCIP index not found: {}", path.display());
    }
    ingest_scip(store, path, repo_root)
        .with_context(|| format!("ingesting {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_ranges() {
        assert_eq!(decode_range(&[10, 4, 9]), (10, 4, 9));
        assert_eq!(decode_range(&[10, 4, 10, 9]), (10, 4, 9));
        assert_eq!(decode_range(&[]), (0, 0, 0));
    }

    #[test]
    fn path_patterns_are_last_resort() {
        // Without a repo root we can only guess from the path, and we say so.
        let (gen, via) = detect_generated("srcgo/schema/x.pb.go", None);
        assert!(gen);
        assert_eq!(via, GeneratedVia::PathPattern);

        // A name that looks ordinary is not flagged - this is the case that burned us.
        let (gen, _) = detect_generated("srcpy/schema/orders_api/__init__.py", None);
        assert!(!gen);
    }

    #[test]
    fn marker_beats_path() {
        let dir = std::env::temp_dir().join("cairn-test-marker");
        let _ = std::fs::create_dir_all(dir.join("sub"));
        let p = dir.join("sub").join("ordinary_name.py");
        std::fs::write(&p, "# Code generated by protoc. DO NOT EDIT.\nx = 1\n").unwrap();
        let (gen, via) = detect_generated("sub/ordinary_name.py", Some(&dir));
        assert!(gen);
        assert_eq!(via, GeneratedVia::HeaderMarker);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
