//! `cairn` — local code navigation for coding agents.
//!
//! CLI rather than an MCP server (architecture D1): an agent runs commands natively,
//! and this way the tool also works in CI, a Makefile and a human terminal. Startup
//! cost is on the hot path (every query is a fresh process), so nothing expensive
//! happens before the subcommand is known.

use anyhow::{Context, Result};
use cairn_store::{ingest, Store};
use clap::{Parser, Subcommand};
use std::path::PathBuf;
use std::process::ExitCode;
use std::time::Instant;

/// Exit codes are part of the contract: an agent must be able to tell "nothing is
/// there" from "I cannot see" (architecture 6.1.1).
mod exit {
    pub const FOUND: u8 = 0;
    pub const NOT_FOUND: u8 = 1;
    pub const ERROR: u8 = 2;
    pub const DEGRADED: u8 = 3;
}

#[derive(Parser)]
#[command(name = "cairn", version, about = "Local code navigation for agents")]
struct Cli {
    /// Index database. Defaults to .cairn/index.sqlite under the current directory.
    #[arg(long, global = true)]
    db: Option<PathBuf>,

    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Load a SCIP index into the store, replacing what is there.
    Index {
        /// One or more .scip files.
        indexes: Vec<PathBuf>,
        /// Repo root, used to detect generated code by header marker rather than by
        /// filename pattern. Strongly recommended: filename patterns lie.
        #[arg(long)]
        repo: Option<PathBuf>,
    },
    /// Find symbols by name.
    Symbol {
        query: String,
        #[arg(long, default_value_t = 15)]
        limit: usize,
    },
    /// Show references to a symbol.
    Refs {
        handle: String,
        #[arg(long)]
        include_generated: bool,
        #[arg(long, default_value_t = 40)]
        limit: usize,
    },
    /// What is indexed, and how stale it is.
    Status,
}

fn main() -> ExitCode {
    match run() {
        Ok(code) => ExitCode::from(code),
        Err(e) => {
            eprintln!("cairn: {e:#}");
            ExitCode::from(exit::ERROR)
        }
    }
}

fn default_db() -> PathBuf {
    PathBuf::from(".cairn/index.sqlite")
}

fn run() -> Result<u8> {
    let cli = Cli::parse();
    let db = cli.db.unwrap_or_else(default_db);

    match cli.cmd {
        Cmd::Index { indexes, repo } => {
            if indexes.is_empty() {
                anyhow::bail!("give at least one .scip file");
            }
            if let Some(parent) = db.parent() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
            let started = Instant::now();
            let mut store = Store::reset(&db)?;
            for path in &indexes {
                let t = Instant::now();
                let stats = ingest::ingest_path(&mut store, path, repo.as_deref())?;
                println!(
                    "{}: {} documents, {} symbols, {} occurrences, {} generated \
                     ({} by marker), prefix {:?}, {} batch flushes in {:.1}s",
                    path.display(),
                    stats.documents,
                    stats.symbols,
                    stats.occurrences,
                    stats.generated_files,
                    stats.marker_detected,
                    stats.path_prefix,
                    stats.batch_flushes,
                    t.elapsed().as_secs_f64()
                );
                if repo.is_some() && stats.generated_files > 0 && stats.marker_detected == 0 {
                    eprintln!(
                        "cairn: warning - {} files flagged generated by path pattern and none \
                         by header marker; the path prefix is probably wrong",
                        stats.generated_files
                    );
                }
            }
            let c = store.counts()?;
            println!(
                "store: {} files, {} symbols, {} occurrences in {:.1}s -> {}",
                c.files,
                c.symbols,
                c.occurrences,
                started.elapsed().as_secs_f64(),
                db.display()
            );
            Ok(exit::FOUND)
        }

        Cmd::Symbol { query, limit } => {
            let store = open(&db)?;
            let rows = store.find_symbols(&query, limit)?;
            let found = !rows.is_empty();
            print!("{}", cairn_fmt::symbols(&rows, &query).render());
            Ok(if found { exit::FOUND } else { exit::NOT_FOUND })
        }

        Cmd::Refs {
            handle,
            include_generated,
            limit,
        } => {
            let store = open(&db)?;
            let Some(symbol_id) = store.resolve_handle(&handle)? else {
                // An unknown handle is a query error, not an empty result: the agent
                // asked about something we cannot even identify.
                eprintln!("cairn: no symbol with handle '{handle}' (run `cairn symbol` first)");
                return Ok(exit::ERROR);
            };
            let sym = store
                .symbol(symbol_id)?
                .context("handle resolved to a missing symbol")?;
            let (refs, suppressed) = store.references(symbol_id, include_generated, limit)?;
            let found = !refs.is_empty();
            print!(
                "{}",
                cairn_fmt::references(&sym, &refs, suppressed).render()
            );
            Ok(if found { exit::FOUND } else { exit::NOT_FOUND })
        }

        Cmd::Status => {
            if !db.exists() {
                println!("no index at {}", db.display());
                println!("degraded: nothing indexed yet - run `cairn index <file.scip>`");
                return Ok(exit::DEGRADED);
            }
            let store = open(&db)?;
            let c = store.counts()?;
            println!("index      {}", db.display());
            println!("files      {}", c.files);
            println!("symbols    {}", c.symbols);
            println!("occurrence {}", c.occurrences);
            println!("generated  {} files", c.generated_files);
            println!("stale: unknown (no snapshot tracking yet)");
            Ok(exit::FOUND)
        }
    }
}

fn open(db: &PathBuf) -> Result<Store> {
    if !db.exists() {
        anyhow::bail!(
            "no index at {} - run `cairn index <file.scip> --repo <dir>` first",
            db.display()
        );
    }
    Store::open(db)
}
