[package]
name = "cairn-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cairn"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
cairn-scip.workspace = true
cairn-store.workspace = true
cairn-fmt.workspace = true
cairn-daemon.workspace = true
blake3.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
rusqlite.workspace = true
serde.workspace = true
serde_yaml.workspace = true
