"""Code generated by protoc-gen-python_betterproto2. DO NOT EDIT.

source: telemetry.proto

Stands in for generator output. Only the names carry meaning here: the indexer folds
``AlertServiceBase`` and ``TelemetryServiceStub`` onto their service declarations by
shape, so they have to be spelled the way the generator spells them.
"""

from dataclasses import dataclass, field


@dataclass
class Reading:
    station_id: str = ""
    celsius: float = 0.0
    humidity: float = 0.0
    observed_at: int = 0
    sensor_fault: bool = False


@dataclass
class ReadingBatch:
    readings: list[Reading] = field(default_factory=list)
    source: str = ""


@dataclass
class IngestAck:
    accepted: int = 0
    rejected: int = 0


@dataclass
class AlertRequest:
    station_id: str = ""
    reason: str = ""
    celsius: float = 0.0


@dataclass
class AlertAck:
    raised: bool = False
    note: str = ""


@dataclass
class StationQuery:
    station_id: str = ""


@dataclass
class StationInfo:
    station_id: str = ""
    label: str = ""
    altitude: int = 0
    retired: bool = False


class AlertServiceBase:
    """Server base for AlertService. Subclasses override the handlers."""

    async def raise_alert(self, request: AlertRequest) -> AlertAck:
        raise NotImplementedError

    async def clear_alert(self, request: AlertRequest) -> AlertAck:
        raise NotImplementedError


class TelemetryServiceStub:
    """Client for TelemetryService, which is served by the Go side."""

    def __init__(self, channel: object) -> None:
        self._channel = channel

    async def upload_readings(self, request: ReadingBatch) -> IngestAck:
        return IngestAck()

    async def describe_station(self, request: StationQuery) -> StationInfo:
        return StationInfo(station_id=request.station_id)
